version: '3.8'

services:
  # Service Prometheus untuk Table-Service
  prometheus-table:
    image: prom/prometheus:v2.44.0
    container_name: prometheus-table
    ports:
      - "9091:9090" # Prometheus baru diakses di localhost:9091
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data_table:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped

  # Service Grafana untuk Table-Service
  grafana-table:
    image: grafana/grafana:9.5.2
    container_name: grafana-table
    ports:
      - "3001:3000" # Grafana baru diakses di localhost:3001
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      # <-- BAGIAN INI SANGAT PENTING DAN SEKARANG DIAKTIFKAN -->
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - grafana_data_table:/var/lib/grafana

volumes:
  prometheus_data_table:
  grafana_data_table: